const WORKS = [
  {
    title: "Beings I",
    titleChinese: "取暖I",
    medium: "Lithography",
    dimensions: '9"x12"',
    category: "printmaking",
    image: "images/IMG_9067.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Beings II",
    titleChinese: "取暖II",
    medium: "Lithography",
    dimensions: '9"x12"',
    category: "printmaking",
    image: "images/IMG_9694.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
 

  // Paintings
  {
    title: "Taking My Brushes For a Walk #1",
    medium: "Oil on canvas",
    dimensions: '30"x30"',
    category: "painting",
    image: "images/IMG_5300.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Taking My Brushes For a Walk #2",
    medium: "Oil on canvas",
    dimensions: '30"x30"',
    category: "painting",
    image: "images/IMG_5306.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Taking My Brushes For a Walk #3",
    medium: "Oil on canvas",
    dimensions: '30"x30"',
    category: "painting",
    image: "images/IMG_5309.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Taking My Brushes For a Walk #4",
    medium: "Oil on canvas",
    dimensions: '30"x30"',
    category: "painting",
    image: "images/IMG_5313.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Remedios",
    medium: "Oil on canvas",
    dimensions: '40"x30"',
    category: "painting",
    image: "images/IMG_5318.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Too Comfortable",
    medium: "Oil on canvas",
    dimensions: '40"x30"',
    category: "painting",
    image: "images/IMG_5320.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Columbus Circle",
    medium: "Oil on canvas",
    dimensions: '36"x24"',
    category: "painting",
    image: "images/IMG_5328.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Untitled",
    medium: "Watercolor on Paper",
    dimensions: "",
    category: "painting",
    image: "images/IMG_5331.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Untitled",
    medium: "Watercolor on Paper",
    dimensions: "",
    category: "painting",
    image: "images/IMG_5333.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Siblings Rivalry",
    medium: "Charcoal on Paper",
    dimensions: '20"x16"',
    category: "painting",
    image: "images/IMG_5336.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Sketch",
    medium: "Oil on canvas",
    dimensions: "",
    category: "painting",
    image: "images/IMG_5340.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Untitled xii",
    medium: "Oil on canvas",
    dimensions: "",
    category: "painting",
    image: "images/IMG_5340-2.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Untitled xiii",
    medium: "Oil on canvas",
    dimensions: "",
    category: "painting",
    image: "images/IMG_5340-3.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  // Sketches — add entries with category: "sketches"
  {
    title: "march 2026",
    medium: "pen on paper",
    dimensions: "",
    category: "sketches",
    image: "images/IMG_9056.jpeg",
    originalAvailable: false,
    shopifyProductId: "",
    description: "Debuted March 26, 2022 at MOMO SUSHI, 239 Park Ave S, New York, NY.",
  },
  {
    title: "march 2026",
    medium: "pen on paper",
    dimensions: "",
    category: "photography",
    image: "images/DSCF0707.jpeg",
    originalAvailable: false,
    shopifyProductId: "",
    description: ".",
  },
  // Photography — add entries with category: "Photography"
  {
    title: "march 2026",
    medium: "pen on paper",
    dimensions: "",
    category: "photography",
    image: "images/DSCF0707.jpeg",
    originalAvailable: false,
    shopifyProductId: "",
    description: ".",
  },
];
