const WORKS = [
  {
    title: "Lotus",
    titleChinese: "荷(hé)",
    medium: "Linoleum block print",
    dimensions: '9" × 9"',
    category: "printmaking",
    image: "images/lotus.jpg",
    originalAvailable: false,
    shopifyProductId: "",
    description: "Drawn from Chinese painting aesthetics and created with passion. Can be framed in a 9×9 inch frame, or mounted with a transparent frame to cast shadow effects on the wall. 4 prints remaining.",
  },
  {
    title: "Peek in Beijing",
    titleChinese: "宫墙",
    medium: "Linocut",
    dimensions: "",
    category: "printmaking",
    image: "images/peek-in-beijing.jpg",
    originalAvailable: false,
    shopifyProductId: "",
    description: "Exploring cultural elements of Northern China — the palace walls that mark the boundary between the imperial and the everyday.",
  },
  {
    title: "Buddhism Gestures",
    medium: "Linocut",
    dimensions: "",
    category: "printmaking",
    image: "images/buddhism-gestures.jpg",
    originalAvailable: false,
    shopifyProductId: "",
    description: "Three mudras: Granting Wishes and Blessings (upper), Tantric Unity (left), and Teaching (right). Made for experimentation; occasionally gifted with print orders.",
  },
  {
    title: "Where Flowers Bloom So Does Hope",
    medium: "Linocut",
    dimensions: "",
    category: "printmaking",
    image: "images/where-flowers-bloom.jpg",
    originalAvailable: false,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Floating Mountain",
    titleChinese: "浮山",
    medium: "Linocut",
    dimensions: "",
    category: "printmaking",
    image: "images/floating-mountain.jpg",
    originalAvailable: false,
    shopifyProductId: "",
    description: "Depicting the tea farm landscapes of Yunnan province in Southern China.",
  },
  {
    title: "Fruits of Passion",
    medium: "Linocut",
    dimensions: "",
    category: "printmaking",
    image: "images/fruits-of-passion.jpg",
    originalAvailable: false,
    shopifyProductId: "",
    description: "Debuted March 26, 2022 at MOMO SUSHI, 239 Park Ave S, New York, NY.",
  },

  // Paintings — add entries with category: "painting"
  // Sketches — add entries with category: "sketches"
];
