const WORKS = [
  {
    title: "!!!!",
    titleChinese: "荷(hé)",
    medium: "Linoleum block print",
    dimensions: '9" × 9"',
    category: "printmaking",
    image: "images/lotus.jpg",
    originalAvailable: false,
    shopifyProductId: "",
    description: "Drawn from Chinese painting aesthetics and created with passion. Can be framed in a 9×9 inch frame, or mounted with a transparent frame to cast shadow effects on the wall. 4 prints remaining.",
  },
  {
    title: "Peek in Beijing",
    titleChinese: "宫墙",
    medium: "Linocut",
    dimensions: "",
    category: "printmaking",
    image: "images/peek-in-beijing.jpg",
    originalAvailable: false,
    shopifyProductId: "",
    description: "Exploring cultural elements of Northern China — the palace walls that mark the boundary between the imperial and the everyday.",
  },
  {
    title: "Buddhism Gestures",
    medium: "Linocut",
    dimensions: "",
    category: "printmaking",
    image: "images/buddhism-gestures.jpg",
    originalAvailable: false,
    shopifyProductId: "",
    description: "Three mudras: Granting Wishes and Blessings (upper), Tantric Unity (left), and Teaching (right). Made for experimentation; occasionally gifted with print orders.",
  },
  {
    title: "Where Flowers Bloom So Does Hope",
    medium: "Linocut",
    dimensions: "",
    category: "printmaking",
    image: "images/where-flowers-bloom.jpg",
    originalAvailable: false,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Floating Mountain",
    titleChinese: "浮山",
    medium: "Linocut",
    dimensions: "",
    category: "printmaking",
    image: "images/floating-mountain.jpg",
    originalAvailable: false,
    shopifyProductId: "",
    description: "Depicting the tea farm landscapes of Yunnan province in Southern China.",
  },
  {
    title: "Fruits of Passion",
    medium: "Linocut",
    dimensions: "",
    category: "printmaking",
    image: "images/fruits-of-passion.jpg",
    originalAvailable: false,
    shopifyProductId: "",
    description: "Debuted March 26, 2022 at MOMO SUSHI, 239 Park Ave S, New York, NY.",
  },

  // Paintings
  {
    title: "Taking My Brushes For a Walk #1",
    medium: "Oil on canvas",
    dimensions: "",
    category: "painting",
    image: "images/IMG_5300.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Taking My Brushes For a Walk #2",
    medium: "Oil on canvas",
    dimensions: "",
    category: "painting",
    image: "images/IMG_5306.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Taking My Brushes For a Walk #3",
    medium: "Oil on canvas",
    dimensions: "",
    category: "painting",
    image: "images/IMG_5309.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Taking My Brushes For a Walk #4",
    medium: "Oil on canvas",
    dimensions: "",
    category: "painting",
    image: "images/IMG_5313.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Taking My Brushes For a Walk #5",
    medium: "Oil on canvas",
    dimensions: "",
    category: "painting",
    image: "images/IMG_5318.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Too Comfortable",
    medium: "Oil on canvas",
    dimensions: "",
    category: "painting",
    image: "images/IMG_5320.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Columbus Circle",
    medium: "Oil on canvas",
    dimensions: "",
    category: "painting",
    image: "images/IMG_5328.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Untitled viii",
    medium: "Watercolor on Paper",
    dimensions: "",
    category: "painting",
    image: "images/IMG_5331.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Untitled ix",
    medium: "Watercolor on Paper",
    dimensions: "",
    category: "painting",
    image: "images/IMG_5333.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Siblings Rivalry",
    medium: "Charcoal on Paper",
    dimensions: "",
    category: "painting",
    image: "images/IMG_5336.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Sketch",
    medium: "Oil on canvas",
    dimensions: "",
    category: "painting",
    image: "images/IMG_5340.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Untitled xii",
    medium: "Oil on canvas",
    dimensions: "",
    category: "painting",
    image: "images/IMG_5340-2.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  {
    title: "Untitled xiii",
    medium: "Oil on canvas",
    dimensions: "",
    category: "painting",
    image: "images/IMG_5340-3.jpg",
    originalAvailable: true,
    shopifyProductId: "",
    description: "",
  },
  // Sketches — add entries with category: "sketches"
  {
    title: "march 2026",
    medium: "pen on paper",
    dimensions: "",
    category: "sketches",
    image: "images/fruits-of-passion.jpg",
    originalAvailable: false,
    shopifyProductId: "",
    description: "Debuted March 26, 2022 at MOMO SUSHI, 239 Park Ave S, New York, NY.",
  },
];
